name: p2plib
description: 'Tooling for encrypted udp datagram peer to peer communication'
version: 1.1.7
homepage: https://github.com/alexandrim0/p2plib-dart

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies: 
  collection: ^1.17.0
  sodium: ^2.1.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
