name: p2plib
description: 'Tooling for encrypted udp datagram peer to peer communication'
version: 1.0.0+0
homepage: https://github.com/alexandrim0/p2plib-dart

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  collection: ^1.16.0
  sodium: ^2.0.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.7
